baseURL = "https://alexeygornostaev.com/"
title = "Alexey Gornostaev"
languageCode = "en-us"
theme = "accujazz"
summaryLength = 21
paginate = 10
rssLimit = 10

[params]
  author = "Alexey Gornostaev"
  description = "Alexey Gornostaev's personal website."
  mainSections = ['posts']

[permalinks]
	post = "/:year/:month/:title/"	