baseURL = "https://alexeygornostaev.com/"
title = "Alexey Gornostaev"
languageCode = "en-us"
theme = "accujazz"
summaryLength = 21
paginate = 10
rssLimit = 10

[params]
  author = "Alexey Gornostaev"
  description = "Hi, I’m Alexey, and this is my personal website."
  preview-image = "/img/preview.jpg"
  favicon = "/favicon.ico"
  icon = "/favicon.png"
  mainSections = ['posts']

[permalinks]
	post = "/:year/:month/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true